### ISSUE TITLE
Vote on renaming this github org to mozmeao

### ISSUE THREAD

**Issue by jgmize** [mozmeao/meta#1]
Use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) please.

**Comment by jgmize** [comment]
@mozmar/meta

**Comment by jgmize** [comment]
Also, feel free to add other public discussion items, columns, etc. to https://github.com/mozmar/meta/projects/1

**Comment by pmac** [comment]
Looks to me like the 👍s have it. Just give me some warning. I'll need to change some info in the basket repo.

**Comment by jgmize** [comment]
> Looks to me like the 👍s have it. Just give me some warning. I'll need to change some info in the basket repo.

@pmac consider yourself warned ;)

@metadave let's plan on doing this tomorrow.

**Comment by glogiotatidis** [comment]
Feel free to merge the above PRs after you rename the org.

I also checked `mozmar/jenkins-pipeline`, `mozmar/status.mozmar.org`, `mozmar/status.ramzom.org` and `mozmar/snippets-stats-proxy`.

**Comment by bookshelfdave** [comment]
I'm thinking of holding off for one day so we can notify the rest of the team, does that sound ok to everyone?

**Comment by jgmize** [comment]
> I'm thinking of holding off for one day so we can notify the rest of the team, does that sound ok to everyone?

No objections to delay; as we discussed earlier this isn't a high priority, I just wanted to get it over with :)

**Comment by bookshelfdave** [comment]
team notified via email

**Comment by bookshelfdave** [comment]
- [x] org renamed
- [x] team notified via email
- [x] `snippets-service`, `status`, and `lumbergh` PR's referenced above merged
